CREATE SCHEMA ESTCASO1_CC1M;
USE ESTCASO1_CC1M;

CREATE TABLE IF NOT EXISTS TABELA_DROP_I(
TABTES_COD INT PRIMARY KEY,
TABTES_NOME VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS TABELA_DROP_I;

CREATE TABLE IF NOT EXISTS FORNECEDORES(
    FORNEC_COD INT PRIMARY KEY,
    FORNEC_NOME VARCHAR(45) NOT NULL,
    FORNEC_RUA VARCHAR(45) NOT NULL,
    FORNEC_NUMRUA INT,
    FORNEC_BAIRRO VARCHAR(45) NOT NULL,
    FORNEC_CIDADE VARCHAR(45) NOT NULL,
    FORNEC_ESTADO VARCHAR(45) NOT NULL,
    FORNEC_PAIS VARCHAR(30) NOT NULL,
    FORNEC_CODPOSTAL VARCHAR(10) NOT NULL,
    FORNEC_TELEFONE VARCHAR(15) NOT NULL,
    FORNEC_CONTATO TEXT NOT NULL
);

ALTER TABLE FORNECEDORES ADD FORNEC_EMAIL VARCHAR(50);
ALTER TABLE FORNECEDORES MODIFY COLUMN FORNEC_EMAIL INT;
ALTER TABLE FORNECEDORES CHANGE COLUMN FORNEC_EMAIL FORNEC_ENDEREÇOEMAIL INT;
ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_ENDEREÇOEMAIL;

CREATE TABLE IF NOT EXISTS PRODUTOS(
    PROD_COD INT PRIMARY KEY,
    PROD_NOME VARCHAR(50) NOT NULL,
    PROD_DESCRICAO TEXT NOT NULL,
    PROD_ESPECTEC TEXT NOT NULL,
    PROD_QUANT DECIMAL(10,3) NOT NULL,
    PROD_PRECOUNIT DECIMAL(10,2) NOT NULL,
    PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
    PROD_ESTOQUEMINIMO DECIMAL(10,3) NOT NULL
);

ALTER TABLE PRODUTOS ADD PROD_NUM INT;
ALTER TABLE PRODUTOS MODIFY COLUMN PROD_NUM VARCHAR(30);
ALTER TABLE PRODUTOS CHANGE COLUMN PROD_NUM PROD_NUMSEC VARCHAR(30);
ALTER TABLE PRODUTOS DROP COLUMN PROD_NUMSEC;

CREATE TABLE IF NOT EXISTS FILIAIS(
    FILIAIS_COD INT PRIMARY KEY,
    FILIAIS_NOME VARCHAR(30) NOT NULL,
    FILIAIS_RUA VARCHAR(100) NOT NULL,
    FILIAIS_NUMRUA INT,
    FILIAIS_BAIRRO VARCHAR(50) NOT NULL,
    FILIAIS_CIDADE VARCHAR(50) NOT NULL,
    FILIAIS_ESTADO VARCHAR(50) NOT NULL,
    FILIAIS_PAIS VARCHAR(50) NOT NULL,
    FILIAIS_CODPOSTAL VARCHAR(10) NOT NULL,
    FILIAIS_CAPACIDADE TEXT NOT NULL
);

ALTER TABLE FILIAIS ADD FILIAIS_LOCAL VARCHAR(30);
ALTER TABLE FILIAIS MODIFY COLUMN FILIAIS_LOCAL TEXT;
ALTER TABLE FILIAIS CHANGE COLUMN FILIAIS_LOCAL FILIAIS_LOCALIDADE TEXT;
ALTER TABLE FILIAIS DROP COLUMN FILIAIS_LOCALIDADE;

CREATE TABLE IF NOT EXISTS PEDIDOS(
    PED_COD INT PRIMARY KEY,
    PED_DATA DATE NOT NULL,
    PED_HORA TIME NOT NULL,
    PED_PREVISAO DATE NOT NULL,
    PED_STATUS ENUM ('PENDENTE', 'CONCLUÍDO', 'EM ESPERA') NOT NULL,
    PED_FORNECEDOR INT NOT NULL,
    CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR)
    REFERENCES FORNECEDORES(FORNEC_COD)
);

ALTER TABLE PEDIDOS ADD PED_FORMATO BLOB;
ALTER TABLE PEDIDOS MODIFY COLUMN PED_FORMATO DECIMAL(10,2);
ALTER TABLE PEDIDOS CHANGE COLUMN PED_FORMATO PED_FORMA DECIMAL;
ALTER TABLE PEDIDOS DROP COLUMN PED_FORMA;

CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
    RECEB_DATA DATE NOT NULL,
    RECEB_HORA TIME NOT NULL,
    RECEB_QUANTPROD DECIMAL(10,3) NOT NULL,
    RECEB_CONDICAO TEXT NOT NULL,
    RECEB_PEDIDOS INT PRIMARY KEY,
    CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) 
    REFERENCES PEDIDOS(PED_COD)
);

ALTER TABLE RECEBIMENTOS ADD RECEB_NUM INT;
ALTER TABLE RECEBIMENTOS MODIFY COLUMN RECEB_NUM TEXT;
ALTER TABLE RECEBIMENTOS CHANGE COLUMN RECEB_NUM RECEB_NUMERO TEXT;
ALTER TABLE RECEBIMENTOS DROP COLUMN RECEB_NUMERO;

CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
    PDPR_PEDIDOS INT,
    PDPR_PRODUTOS INT,
    PDPR_QUANT DECIMAL(10,3) NOT NULL,
    PRIMARY KEY(PDPR_PEDIDOS, PDPR_PRODUTOS),
    CONSTRAINT PDPR_FK_PEDIDOS FOREIGN KEY(PDPR_PEDIDOS)
    REFERENCES PEDIDOS(PED_COD),
    CONSTRAINT PDPR_FK_PRODUTOS FOREIGN KEY(PDPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE PEDIDOS_PRODUTOS ADD PEDIDOS_PRODUTOS_COD INT;
ALTER TABLE PEDIDOS_PRODUTOS MODIFY COLUMN PEDIDOS_PRODUTOS_COD CHAR(12);
ALTER TABLE PEDIDOS_PRODUTOS CHANGE COLUMN PEDIDOS_PRODUTOS_COD PEDIDOS_PRODUTOS_CODIGO CHAR(12);
ALTER TABLE PEDIDOS_PRODUTOS DROP COLUMN PEDIDOS_PRODUTOS_CODIGO;

CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
    FLPR_FILIAIS INT,
    FLPR_PRODUTOS INT,
    FLPR_QUANT DECIMAL (10,3) NOT NULL,
    PRIMARY KEY(FLPR_FILIAIS, FLPR_PRODUTOS),
    CONSTRAINT FLPR_FK_FILIAIS FOREIGN KEY(FLPR_FILIAIS)
    REFERENCES FILIAIS(FILIAIS_COD),
    CONSTRAINT FLPR_FK_PRODUTOS FOREIGN KEY(FLPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FILIAIS_PRODUTOS ADD FILIAIS_PRODUTOS_CADASTRO VARCHAR(30);
ALTER TABLE FILIAIS_PRODUTOS MODIFY COLUMN FILIAIS_PRODUTOS_CADASTRO DATETIME;
ALTER TABLE FILIAIS_PRODUTOS CHANGE COLUMN FILIAIS_PRODUTOS_CADASTRO FILIAIS_PRODUTOS_LOGIN DATETIME;
ALTER TABLE FILIAIS_PRODUTOS DROP COLUMN FILIAIS_PRODUTOS_LOGIN;

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
    FRPR_FORNECEDORES INT,
    FRPR_PRODUTOS INT,
    PRIMARY KEY(FRPR_FORNECEDORES, FRPR_PRODUTOS),
    CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDORES)
    REFERENCES FORNECEDORES(FORNEC_COD),
    CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS)
    REFERENCES PRODUTOS(PROD_COD)
);

ALTER TABLE FORNECEDORES_PRODUTOS ADD FORNECEDORES_PRODUTOS_TELEFONE TIME;
ALTER TABLE FORNECEDORES_PRODUTOS MODIFY COLUMN FORNECEDORES_PRODUTOS_TELEFONE INT;
ALTER TABLE FORNECEDORES_PRODUTOS CHANGE COLUMN FORNECEDORES_PRODUTOS_TELEFONE FORNECEDORES_PRODUTOS_CELULAR INT;
ALTER TABLE FORNECEDORES_PRODUTOS DROP COLUMN FORNECEDORES_PRODUTOS_CELULAR;
